"""
Synchronization API Endpoints
Endpoints for syncing data from Ingest system
"""

from typing import Optional, Dict, Any
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException, status, BackgroundTasks, Header
from sqlalchemy.ext.asyncio import AsyncSession
from pydantic import BaseModel, Field
import structlog

from app.db.session import get_db
from app.services.sync_service import SyncService
from app.core.security import verify_api_key
from app.config.settings import settings

logger = structlog.get_logger()
router = APIRouter()


# Request/Response Models
class EmbeddingData(BaseModel):
    """
    Embedding data model for a single document chunk.
    
    Attributes:
        id: Unique UUID for this embedding (generated by Ingest)
        vector: Embedding vector (768-dim for multilingual-e5-base)
        text: Full text content of the document chunk
        document_id: ID of the source document
        document_type: Type of document (LAW, REGULATION, etc.)
        chunk_index: Index of this chunk in the document
        language: Language code (fa, en, etc.)
        source: Source system (ingest, manual, etc.)
        metadata: Additional metadata (work_title, doc_type, etc.)
    """
    id: str = Field(..., description="Unique UUID for this embedding")
    vector: list[float] = Field(..., description="Embedding vector (768 dimensions)")
    text: str = Field(..., description="Full text content")
    document_id: str = Field(..., description="Source document ID")
    document_type: Optional[str] = Field(None, description="Document type (LAW, REGULATION, etc.)")
    chunk_index: Optional[int] = Field(None, description="Chunk index in document")
    language: Optional[str] = Field("fa", description="Language code (fa, en, etc.)")
    source: Optional[str] = Field("ingest", description="Source system")
    created_at: Optional[str] = Field(None, description="Creation timestamp")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")


class SyncEmbeddingsRequest(BaseModel):
    """
    Request to sync embeddings from Ingest to Core.
    
    Attributes:
        embeddings: List of embeddings to sync
        sync_type: Type of sync (incremental or full)
    """
    embeddings: list[EmbeddingData] = Field(..., description="List of embeddings to sync")
    sync_type: str = Field(default="incremental", description="Sync type: 'incremental' or 'full'")


class SyncStatusResponse(BaseModel):
    """
    Current sync status between Ingest and Core.
    
    Attributes:
        last_sync: Timestamp of last successful sync
        pending_count: Number of pending sync jobs
        synced_count: Number of successfully synced items
        error_count: Number of failed sync jobs
        qdrant_status: Current Qdrant collection status
    """
    last_sync: Optional[str] = Field(None, description="Last sync timestamp (ISO 8601)")
    pending_count: int = Field(..., description="Number of pending items")
    synced_count: int = Field(..., description="Number of synced items")
    error_count: int = Field(..., description="Number of failed items")
    qdrant_status: Dict[str, Any] = Field(..., description="Qdrant collection info")


class SyncStatisticsResponse(BaseModel):
    """
    Complete statistics from Core system.
    
    Attributes:
        timestamp: Current timestamp
        postgresql: Statistics from Core PostgreSQL database
        qdrant: Statistics from Qdrant vector database
        summary: Summary of all statistics
    """
    timestamp: str = Field(..., description="Current timestamp (ISO 8601)")
    postgresql: Dict[str, Any] = Field(..., description="PostgreSQL statistics")
    qdrant: Dict[str, Any] = Field(..., description="Qdrant statistics")
    summary: Dict[str, Any] = Field(..., description="Summary statistics")


class NodeDetailResponse(BaseModel):
    """
    Complete information about a single node in Qdrant.
    
    This response includes all stored information for verification purposes.
    
    Attributes:
        node_id: Original UUID from Ingest
        exists: Whether the node exists in Qdrant
        vector: Full embedding vector
        text: Complete text content
        document_id: Source document ID
        document_type: Type of document (LAW, REGULATION, etc.)
        chunk_index: Index of this chunk in the document
        language: Language code (fa, en, etc.)
        source: Source system (ingest, manual, etc.)
        metadata: Complete metadata object
        created_at: Creation timestamp
        updated_at: Last update timestamp
        vector_dimensions: Available vector fields and their dimensions
    """
    node_id: str = Field(..., description="Original UUID from Ingest")
    exists: bool = Field(..., description="Whether node exists in Qdrant")
    vector: Optional[list[float]] = Field(None, description="Full embedding vector")
    text: Optional[str] = Field(None, description="Complete text content")
    document_id: Optional[str] = Field(None, description="Source document ID")
    document_type: Optional[str] = Field(None, description="Document type (LAW, REGULATION, etc.)")
    chunk_index: Optional[int] = Field(None, description="Chunk index in document")
    language: Optional[str] = Field(None, description="Language code (fa, en, etc.)")
    source: Optional[str] = Field(None, description="Source system (ingest, manual, etc.)")
    metadata: Optional[Dict[str, Any]] = Field(None, description="Complete metadata object")
    created_at: Optional[str] = Field(None, description="Creation timestamp (ISO 8601)")
    updated_at: Optional[str] = Field(None, description="Last update timestamp (ISO 8601)")
    vector_dimensions: Optional[Dict[str, int]] = Field(None, description="Available vector fields and dimensions")


# API key dependency
async def verify_sync_api_key(x_api_key: str = Header(..., alias="X-API-Key")):
    """Verify API key for sync operations."""
    if not verify_api_key(x_api_key):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid API key"
        )
    return x_api_key


# Sync embeddings endpoint
@router.post("/embeddings", tags=["Sync"])
async def sync_embeddings(
    request: SyncEmbeddingsRequest,
    background_tasks: BackgroundTasks,
    api_key: str = Depends(verify_sync_api_key)
):
    """
    Sync embeddings from Ingest system to Core Qdrant database.
    
    This endpoint receives embeddings from the Ingest system and stores them in Qdrant.
    Each embedding must have a unique UUID (node_id) generated by Ingest.
    
    **Authentication:** Requires API Key in X-API-Key header
    
    **Returns:**
    - status: "success" or "failed"
    - synced_count: Number of embeddings successfully synced
    - node_ids: List of node IDs that were synced
    - timestamp: Sync completion timestamp
    
    **Example:**
    ```json
    {
      "embeddings": [
        {
          "id": "550e8400-e29b-41d4-a716-446655440000",
          "vector": [0.123, -0.456, ...],
          "text": "ماده ۱ - این قانون...",
          "document_id": "doc-12345",
          "metadata": {"work_title": "قانون..."}
        }
      ]
    }
    ```
    """
    try:
        sync_service = SyncService()
        
        # Process embeddings
        embeddings_data = []
        node_ids = []  # Track node IDs
        
        for emb in request.embeddings:
            embeddings_data.append({
                "id": emb.id,
                "vector": emb.vector,
                "text": emb.text,
                "document_id": emb.document_id,
                "document_type": emb.document_type,
                "chunk_index": emb.chunk_index,
                "language": emb.language,
                "source": emb.source,
                "created_at": emb.created_at,
                "metadata": emb.metadata
            })
            node_ids.append(emb.id)
        
        # Sync to Qdrant (using "medium" vector field for 768-dim embeddings)
        synced_count = await sync_service.qdrant_service.upsert_embeddings(
            embeddings_data,
            vector_field="medium"  # For multilingual-e5-base (768 dim)
        )
        
        logger.info(
            f"Synced {synced_count} embeddings",
            sync_type=request.sync_type
        )
        
        return {
            "status": "success",
            "synced_count": synced_count,
            "node_ids": node_ids,  # Return list of node IDs
            "timestamp": datetime.utcnow().isoformat()
        }
        
    except Exception as e:
        logger.error(f"Sync failed: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Sync failed: {str(e)}"
        )


# Trigger full sync
@router.post("/trigger-full-sync")
async def trigger_full_sync(
    background_tasks: BackgroundTasks,
    api_key: str = Depends(verify_sync_api_key)
):
    """
    Trigger a full synchronization from Ingest pgvector to Qdrant.
    
    This is a heavy operation and should be run carefully.
    """
    try:
        # Run sync in background
        background_tasks.add_task(run_full_sync)
        
        return {
            "status": "initiated",
            "message": "Full sync started in background"
        }
        
    except Exception as e:
        logger.error(f"Failed to trigger sync: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to trigger sync: {str(e)}"
        )


# Get sync status
@router.get("/status", response_model=SyncStatusResponse)
async def get_sync_status(
    api_key: str = Depends(verify_sync_api_key)
):
    """Get current synchronization status."""
    try:
        sync_service = SyncService()
        status = await sync_service.get_sync_status()
        
        return SyncStatusResponse(
            last_sync=status.get("last_sync"),
            pending_count=status.get("sync_jobs", {}).get("pending", 0),
            synced_count=status.get("qdrant", {}).get("points_count", 0),
            error_count=status.get("sync_jobs", {}).get("error", 0),
            qdrant_status=status.get("qdrant", {})
        )
        
    except Exception as e:
        logger.error(f"Failed to get status: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to get status: {str(e)}"
        )


# Process sync queue
@router.post("/process-queue")
async def process_sync_queue(
    background_tasks: BackgroundTasks,
    api_key: str = Depends(verify_sync_api_key)
):
    """
    Process pending items from sync queue.
    
    This reads from the Ingest sync queue table and processes pending jobs.
    """
    try:
        sync_service = SyncService()
        result = await sync_service.sync_from_sync_queue()
        
        return {
            "status": "success",
            "processed": result.get("total_processed", 0),
            "success": result.get("total_success", 0),
            "errors": result.get("total_errors", 0),
            "duration": result.get("duration", 0)
        }
        
    except Exception as e:
        logger.error(f"Queue processing failed: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Queue processing failed: {str(e)}"
        )


# Delete document embeddings
@router.delete("/document/{document_id}", tags=["Sync"])
async def delete_document_embeddings(
    document_id: str,
    api_key: str = Depends(verify_sync_api_key)
):
    """
    Delete all embeddings for a specific document.
    
    **Authentication:** Requires API Key in X-API-Key header
    
    **Parameters:**
    - document_id: The document ID whose embeddings should be deleted
    
    **Returns:**
    - status: "success" or "failed"
    - document_id: The document ID that was deleted
    - deleted: Number of embeddings deleted
    """
    try:
        sync_service = SyncService()
        deleted = await sync_service.qdrant_service.delete_by_document_id(
            document_id
        )
        
        return {
            "status": "success",
            "document_id": document_id,
            "deleted": deleted
        }
        
    except Exception as e:
        logger.error(f"Delete failed: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Delete failed: {str(e)}"
        )


# Delete single node by node_id
@router.delete("/node/{node_id}", tags=["Sync"])
async def delete_node(
    node_id: str,
    api_key: str = Depends(verify_sync_api_key)
):
    """
    Delete a single node from Qdrant by its node_id.
    
    This allows Ingest to delete a specific node using the same UUID
    it used when creating the node.
    
    **Authentication:** Requires API Key in X-API-Key header
    
    **Parameters:**
    - node_id: The UUID of the node to delete (same as sent by Ingest)
    
    **Returns:**
    - status: "success" or "failed"
    - node_id: The node ID that was deleted
    - deleted: True if deleted, False if not found
    
    **Example:**
    ```bash
    DELETE /api/v1/sync/node/550e8400-e29b-41d4-a716-446655440000
    Header: X-API-Key: ...
    ```
    
    **Response:**
    ```json
    {
      "status": "success",
      "node_id": "550e8400-e29b-41d4-a716-446655440000",
      "deleted": true
    }
    ```
    """
    try:
        from app.services.qdrant_service import QdrantService
        
        qdrant_service = QdrantService()
        deleted = await qdrant_service.delete_point(node_id)
        
        return {
            "status": "success" if deleted else "failed",
            "node_id": node_id,
            "deleted": deleted
        }
        
    except Exception as e:
        logger.error(f"Delete node failed: {e}", node_id=node_id)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to delete node: {str(e)}"
        )


# Update single node by node_id
@router.put("/node/{node_id}", tags=["Sync"])
async def update_node(
    node_id: str,
    request: EmbeddingData,
    api_key: str = Depends(verify_sync_api_key)
):
    """
    Update a single node in Qdrant by its node_id.
    
    This allows Ingest to update a specific node using the same UUID.
    The update is performed using upsert, so if the node doesn't exist,
    it will be created.
    
    **Authentication:** Requires API Key in X-API-Key header
    
    **Parameters:**
    - node_id: The UUID of the node to update (must match request.id)
    - request: Updated embedding data
    
    **Returns:**
    - status: "success" or "failed"
    - node_id: The node ID that was updated
    - action: "updated" or "created"
    
    **Example:**
    ```bash
    PUT /api/v1/sync/node/550e8400-e29b-41d4-a716-446655440000
    Header: X-API-Key: ...
    Body: {
      "id": "550e8400-e29b-41d4-a716-446655440000",
      "vector": [0.123, ...],
      "text": "متن جدید",
      "document_id": "doc-123",
      "metadata": {...}
    }
    ```
    
    **Response:**
    ```json
    {
      "status": "success",
      "node_id": "550e8400-e29b-41d4-a716-446655440000",
      "action": "updated"
    }
    ```
    """
    try:
        # Validate that node_id matches request.id
        if node_id != request.id:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"node_id in URL ({node_id}) must match id in request body ({request.id})"
            )
        
        from app.services.qdrant_service import QdrantService
        
        qdrant_service = QdrantService()
        
        # Check if node exists
        existing = await qdrant_service.get_point(node_id)
        action = "updated" if existing else "created"
        
        # Upsert the node
        await qdrant_service.upsert_embeddings(
            [{
                "id": request.id,
                "vector": request.vector,
                "text": request.text,
                "document_id": request.document_id,
                "document_type": request.document_type,
                "chunk_index": request.chunk_index,
                "language": request.language,
                "source": request.source,
                "created_at": request.created_at,
                "metadata": request.metadata
            }],
            vector_field="medium"
        )
        
        return {
            "status": "success",
            "node_id": node_id,
            "action": action
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Update node failed: {e}", node_id=node_id)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to update node: {str(e)}"
        )


# Get complete statistics
@router.get("/statistics", response_model=SyncStatisticsResponse, tags=["Sync"])
async def get_sync_statistics(
    api_key: str = Depends(verify_sync_api_key)
):
    """
    Get complete statistics from Core system.
    
    Returns comprehensive statistics from both Core PostgreSQL database
    and Qdrant vector database. Useful for monitoring and dashboards.
    
    **Authentication:** Requires API Key in X-API-Key header
    
    **Returns:**
    - **postgresql**: Statistics from Core database
      - users: Total users, breakdown by tier
      - conversations: Total conversations and messages
      - messages: User/assistant message counts, tokens, processing time
      - cache: Query cache statistics
      - feedback: User feedback statistics
    - **qdrant**: Vector database statistics
      - Total points (nodes)
      - Vectors count
      - Indexed vectors
      - Collection status
    - **summary**: Aggregated summary statistics
    
    **Example Response:**
    ```json
    {
      "timestamp": "2024-11-05T10:30:00",
      "postgresql": {
        "users": {"total": 150, "by_tier": {"free": 100, "premium": 50}},
        "conversations": {"total": 500},
        "messages": {"total": 2000}
      },
      "qdrant": {
        "collection_name": "legal_documents",
        "points_count": 10000,
        "status": "green"
      },
      "summary": {
        "total_users": 150,
        "total_vectors": 10000
      }
    }
    ```
    """
    try:
        sync_service = SyncService()
        stats = await sync_service.get_complete_statistics()
        
        return SyncStatisticsResponse(
            timestamp=stats["timestamp"],
            postgresql=stats["postgresql"],
            qdrant=stats["qdrant"],
            summary=stats["summary"]
        )
        
    except Exception as e:
        logger.error(f"Failed to get statistics: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to get statistics: {str(e)}"
        )


# Get node details by ID
@router.get("/node/{node_id}", response_model=NodeDetailResponse, tags=["Sync"])
async def get_node_details(
    node_id: str,
    api_key: str = Depends(verify_sync_api_key)
):
    """
    Get complete information about a specific node in Qdrant.
    
    This endpoint allows the Ingest system to verify that data was correctly
    sent and stored in the Core system. All information stored in Qdrant
    is returned for verification purposes.
    
    **Authentication:** Requires API Key in X-API-Key header
    
    **Parameters:**
    - node_id: The UUID of the node to retrieve (same as sent by Ingest)
    
    **Returns:**
    Complete node information including:
    - Original UUID (node_id)
    - Full embedding vector (768 or 3072 dimensions)
    - Complete text content
    - Document metadata (type, language, source, etc.)
    - Timestamps (created_at, updated_at)
    - Vector dimensions info
    
    **Example Response:**
    ```json
    {
      "node_id": "550e8400-e29b-41d4-a716-446655440000",
      "exists": true,
      "vector": [0.123, -0.456, ...],
      "text": "ماده ۱ - این قانون...",
      "document_id": "doc-12345",
      "document_type": "LAW",
      "chunk_index": 0,
      "language": "fa",
      "source": "ingest",
      "metadata": {...},
      "created_at": "2024-11-05T10:30:00",
      "vector_dimensions": {"medium": 768}
    }
    ```
    
    If node doesn't exist, returns `exists: false` with null values.
    """
    try:
        from app.services.qdrant_service import QdrantService
        
        qdrant_service = QdrantService()
        
        # Retrieve the point from Qdrant
        point = await qdrant_service.get_point(node_id)
        
        if not point:
            return NodeDetailResponse(
                node_id=node_id,
                exists=False
            )
        
        # Extract vector dimensions info
        vector_dims = {}
        if hasattr(point, 'vector') and point.vector:
            if isinstance(point.vector, dict):
                # Named vectors
                for name, vec in point.vector.items():
                    if isinstance(vec, list):
                        vector_dims[name] = len(vec)
            elif isinstance(point.vector, list):
                # Single default vector
                vector_dims['default'] = len(point.vector)
        
        # Get the primary vector (medium for 768-dim or default)
        primary_vector = None
        if hasattr(point, 'vector') and point.vector:
            if isinstance(point.vector, dict):
                # Try to get 'medium' first (768-dim), then 'default'
                primary_vector = point.vector.get('medium') or point.vector.get('default')
            elif isinstance(point.vector, list):
                primary_vector = point.vector
        
        # Extract payload
        payload = point.payload if hasattr(point, 'payload') else {}
        
        # Get original node_id from payload (if stored) or use the provided one
        original_node_id = payload.get('node_id', node_id)
        
        return NodeDetailResponse(
            node_id=original_node_id,  # برگرداندن UUID اصلی
            exists=True,
            vector=primary_vector,
            text=payload.get('text'),
            document_id=payload.get('document_id'),
            document_type=payload.get('document_type'),
            chunk_index=payload.get('chunk_index'),
            language=payload.get('language'),
            source=payload.get('source'),
            metadata=payload.get('metadata', {}),
            created_at=payload.get('created_at'),
            updated_at=payload.get('updated_at'),
            vector_dimensions=vector_dims
        )
        
    except Exception as e:
        logger.error(f"Failed to get node details: {e}", node_id=node_id)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to retrieve node: {str(e)}"
        )


# Helper functions
async def run_full_sync():
    """Run full synchronization in background."""
    try:
        sync_service = SyncService()
        result = await sync_service.sync_embeddings_from_pgvector(
            batch_size=100
        )
        
        logger.info(
            "Full sync completed",
            total_processed=result.get("total_processed"),
            total_synced=result.get("total_synced"),
            duration=result.get("duration")
        )
        
    except Exception as e:
        logger.error(f"Full sync failed: {e}")
